const express=require('express')
const router=express.Router()
const {Home,SignUp,CreatePage1,sendMail,ProfiePage,Login,LoginCheck,ForgotPassword}=require('./../Controller/Usercontroller')
router.route('/Home').get(Home)
router.route('/SignUp').get(SignUp)
router.route('/Create').post(CreatePage1)
router.route('/submitform').post(sendMail)
router.route('/Profile').post(ProfiePage)
router.route('/LoginPage').get(Login)
router.route('/LoginValidation').post(LoginCheck)
router.route('/Forgot').get(ForgotPassword)
module.exports=router
